// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma Migrate / db push require a direct (unpooled) connection. Neon's pooled
// URL (-pooler host) fails with P1001 / prepared-statement errors, so derive a
// direct connection from DATABASE_URL unless an explicit one is provided.
function directOrPooledUrl() {
  const url = process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"];
  if (!url) return undefined;
  try {
    const parsed = new URL(url);
    parsed.hostname = parsed.hostname.replace("-pooler", "");
    parsed.searchParams.delete("pgbouncer");
    return parsed.toString();
  } catch {
    return url;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directOrPooledUrl(),
  },
});
